version: '3.3'

networks:
  blockchain:
    external: false
  loadbalancer_default:
    external: true

services:

  bootstrap:
    image: ammar2017/ethereum-gethclient
    build: ./eth-geth-client
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname ==  bankinstance7-worker]
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    domainname: monifair.com
    networks:
      - blockchain
      - loadbalancer_default
    environment:
      SERVICE_NAME: ethereum
      SERVICE_TAGS: production
      NODE_ENV:   development
      DNSDOMAIN: ${DNSDOMAIN}
    links:
      - netstats
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain/ --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322   --rpcapi="db,personal,eth,net,web3,shh,txpool,admin,miner,debug" --rpccorsdomain="*" --networkid=456719 --rpc  --rpcport="8545" --rpcaddr="0.0.0.0"  --maxpeers 100 --nat "any"  --mine --minerthreads 8'
    volumes:
       - "/eth-geth-client/BlockchainEthereumFiles2/password:/root/BlockchainEthereumFiles2/password:ro"
       - "/eth-geth-client/BlockchainEthereumFiles2/genesis.json:/root/BlockchainEthereumFiles2/genesis.json:ro"
       - "/eth-geth-client/BlockchainEthereumFiles2/keystore:/root/.ethereum/devchain/keystore:rw"
       - "/etc/localtime:/etc/localtime"


  ethereum:
    image: ammar2017/ethereum-gethclient
    build: ./eth-geth-client
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname  == bankinstance7-worker]
    restart: on-failure
    hostname: ethereum
    domainname: monifair.com
    networks:
      - blockchain
      - loadbalancer_default
    environment:
      SERVICE_NAME: ethereum
      SERVICE_TAGS: production
      NODE_ENV:  development
      DNSDOMAIN: ${DNSDOMAIN}
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain/ --rpccorsdomain="*" --networkid=456719 --rpcapi="db,personal,eth,net,web3,shh,txpool,admin,miner,debug" --rpc  --rpcaddr "0.0.0.0" --rpcport="8545"  --maxpeers 100 --nat "any"   --mine --minerthreads 8 --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303"'
    volumes:
       - "/eth-geth-client/BlockchainEthereumFiles2/password:/root/BlockchainEthereumFiles2/password:ro"
       - "/eth-geth-client/BlockchainEthereumFiles2/genesis.json:/root/BlockchainEthereumFiles2/genesis.json:ro"
       - "/eth-geth-client/BlockchainEthereumFiles2/keystore:/root/.ethereum/devchain/keystore:rw"
       - "/etc/localtime:/etc/localtime"
    #ports:
    #  - "30303:30303"
    #  - "30303:30303/udp"
    #  - "8545:8545"
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"


  netstats:
    image: ammar2017/ethereum-netstats
    build: ./eth-netstats
    restart: on-failure
    container_name: netstats
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.hostname  == bankinstance7-worker]
    networks:
      - blockchain
      - loadbalancer_default
    container_name: netstats
    environment:
      WS_SECRET: eth-net-stats-secret
      SERVICE_NAME: netstats
      SERVICE_TAGS: production
      NODE_ENV:  development
      DNSDOMAIN: ${DNSDOMAIN}
    volumes:
      - /etc/localtime:/etc/localtime:rw
    #ports:
    #  - "3000:3000"
    restart: on-failure
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"
