version: '3'
networks:
  frontend:
    external: false
  loadbalancer_default:
    external: true
  microservices_microservices:
    external: true

services:
  web:
    image: ammar2017/web:latest
    build: ./web
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
      - loadbalancer_default
      - microservices_microservices
    environment:
      SERVICE_NAME: frontend__web
      SERVICE_TAGS: production
    ports:
      - "81:443"
    hostname: bankinstance3
    domainname: monifair.com
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"
    restart: always

  backofficeweb:
    image: ammar2017/backofficeweb:latest
    build: ./backofficeweb
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager]
    restart: always
    environment:
      SERVICE_NAME: frontend_backofficeweb
      SERVICE_TAGS: production
    networks:
      - frontend
      - loadbalancer_default
      - microservices_microservices
    ports:
      - "84:443"
    hostname: bankinstance3
    domainname: monifair.com
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"
