version: '3'

networks:
  logging_logging_default:
    external: false
  loadbalancer_loadbalancer_default:
    external: true

services:

elk:
  image: fintechinnovation/elk
  build: ./elk
  network_mode: host
  deploy:
    mode: replicated
    replicas: 3
    placement:
      constraints: [node.role == manager]
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5000:5000"
    - "5044:5044"
  networks:
    - loadbalancer_loadbalancer_default
    - logging_logging_default
  restart: always
