version: '3'

networks:
  microservices:
    external: false
  loadbalancer_default:
    external: true

services:
  authenticationservice:
    image: ammar2017/authenticationservice
    build: ./authenticationservice
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager]
    networks:
      - microservices
      - loadbalancer_default
    environment:
      SERVICE_NAME: authenticationservice
      SERVICE_TAGS: production
      NODE_ENV: production
      hostname: authenticationservice
      DNSDOMAIN: ${DNSDOMAIN}
      TRACE_SERVICE_NAME: authenticationservice
      TRACE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NmY0ZDE1ZTg2OTYyMzg2NzA0NTEwOSIsImlhdCI6MTUwMDQ2NjQ1M30.r6BHvTt3RCkYsTe_U36lAED_t8xtJRKFFEgVAkN8jNE
    ports:
      - "8040:8040"
      - "9901:9901"
    restart: always
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"


  backofficeservice:
    image: ammar2017/backofficeservice
    build: ./backofficeservice
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - microservices
      - loadbalancer_default
    environment:
      SERVICE_NAME: backofficeservice
      SERVICE_TAGS: production
      NODE_ENV: production
      CONSUL_ADDRESS: consul:8500
      DNSDOMAIN: ${DNSDOMAIN}
      TRACE_SERVICE_NAME: backofficeservice
      TRACE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NmY0ZDE1ZTg2OTYyMzg2NzA0NTEwOSIsImlhdCI6MTUwMDQ2NjQ1M30.r6BHvTt3RCkYsTe_U36lAED_t8xtJRKFFEgVAkN8jNE
      RABBITMQ_URL: 'amqps://rabbitmq:rabbitmq@rabbit3:5671/'
    ports:
      - "8050:8050"
      - "9923:9923"
    links:
      - backofficemongo
      - backofficetokenredis
    restart: always
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  backofficemongo:
    image: ammar2017/mongo:latest
    command: --smallfiles
    restart: always
    ports:
      - "27018:27017"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - microservices
      - loadbalancer_default
    environment:
      SERVICE_NAME: backofficemongo
      SERVICE_TAGS: production
      DNSDOMAIN: ${DNSDOMAIN}
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"


  userandaccountservice:
    image: ammar2017/userandaccountservice:latest
    build: ./userandaccountservice
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - microservices
      - loadbalancer_default
    environment:
      SERVICE_NAME: userandaccountservice
      SERVICE_TAGS: production
      NODE_ENV: production
      DNSDOMAIN: ${DNSDOMAIN}
      TRACE_SERVICE_NAME: userandaccountservice
      TRACE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NmY0ZDE1ZTg2OTYyMzg2NzA0NTEwOSIsImlhdCI6MTUwMDQ2NjQ1M30.r6BHvTt3RCkYsTe_U36lAED_t8xtJRKFFEgVAkN8jNE
    ports:
      - "8039:8039"
      - "9003:9003"
    restart: always
    depends_on:
      - historyservice
      - usermongo
      - userandaccountredis
      - tokenredis
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  userandaccountredis:
    image: redis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    restart: always
    ports:
      - "6374:6379"
    networks:
      - microservices
      - loadbalancer_default
    environment:
      SERVICE_NAME: userandaccountredis
      SERVICE_TAGS: production
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  tokenredis:
    image: redis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    restart: always
    ports:
      - "6373:6379"
    networks:
      - loadbalancer_default
    environment:
      SERVICE_NAME: tokenredis
      SERVICE_TAGS: production
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  backofficetokenredis:
    image: redis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    restart: always
    ports:
      - "6372:6379"
    networks:
      - microservices
      - loadbalancer_default
    environment:
      SERVICE_NAME: backofficetokenredis
      SERVICE_TAGS: production
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  usermongo:
    image: ammar2017/mongo:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: --smallfiles
    restart: always
    ports:
      - "27016:27017"
    networks:
      - microservices
      - loadbalancer_default
    environment:
      SERVICE_NAME: microservices_usermongo
      SERVICE_TAGS: production
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  socketservice:
    image: ammar2017/socketservice
    build: ./socketservice
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      SERVICE_NAME: socketservice
      SERVICE_TAGS: production,iphash
      NODE_ENV: production
      CONSUL_ADDRESS: consul:8500
      DNSDOMAIN: ${DNSDOMAIN}
      TRACE_SERVICE_NAME: socketservice
      TRACE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NmY0ZDE1ZTg2OTYyMzg2NzA0NTEwOSIsImlhdCI6MTUwMDQ2NjQ1M30.r6BHvTt3RCkYsTe_U36lAED_t8xtJRKFFEgVAkN8jNE
    ports:
      - "8038:8038"
      - "9904:9904"
    networks:
      - microservices
      - loadbalancer_default
    restart: always
    depends_on:
      - userandaccountservice
      - transactionservice
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  messageservice:
    image: ammar2017/messageservice
    build: ./messageservice
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - microservices
      - loadbalancer_default
    environment:
      SERVICE_NAME: messageservice
      SERVICE_TAGS: production
      NODE_ENV: production
      DNSDOMAIN: ${DNSDOMAIN}
      TRACE_SERVICE_NAME: messageservice
      TRACE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NmY0ZDE1ZTg2OTYyMzg2NzA0NTEwOSIsImlhdCI6MTUwMDQ2NjQ1M30.r6BHvTt3RCkYsTe_U36lAED_t8xtJRKFFEgVAkN8jNE
    links:
      - messageservicemongo
      - pushnotificationserviceredis
    ports:
      - "8037:8037"
      - "9005:9005"
    restart: always
    depends_on:
      - messageservicemongo
      - pushnotificationserviceredis
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  pushnotificationserviceredis:
    image: redis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - microservices
      - loadbalancer_default
    ports:
      - "6371:6379"
    restart: always
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  messageservicemongo:
    image: ammar2017/mongo:latest
    command: --smallfiles
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - microservices
      - loadbalancer_default
    ports:
      - "27015:27017"
    restart: always
    environment:
      SERVICE_NAME: messageservicemongo
      SERVICE_TAGS: production
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  historyservice:
    image: ammar2017/historyservice
    build: ./historyservice
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager]
    environment:
      SERVICE_NAME: historyservice
      SERVICE_TAGS: production
      NODE_ENV: production
      CONSUL_ADDRESS: consul:8500
      DNSDOMAIN: ${DNSDOMAIN}
      TRACE_SERVICE_NAME: historyservice
      TRACE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NmY0ZDE1ZTg2OTYyMzg2NzA0NTEwOSIsImlhdCI6MTUwMDQ2NjQ1M30.r6BHvTt3RCkYsTe_U36lAED_t8xtJRKFFEgVAkN8jNE
    networks:
      - microservices
      - loadbalancer_default
    ports:
      - "8051:8051"
      - "9900:9900"
    restart: always
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  historymongo:
    image: ammar2017/mongo:latest
    command: --smallfiles
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager]
    restart: always
    ports:
       - "27014:27017"
    networks:
      - microservices
      - loadbalancer_default
    environment:
      SERVICE_NAME: historymongo
      SERVICE_TAGS: production
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  transactionservice:
    image: ammar2017/transactionservice
    build: ./transactionservice
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role  ==  manager]
    networks:
      - microservices
      - loadbalancer_default
    environment:
      SERVICE_NAME: transactionservice
      SERVICE_TAGS: production
      NODE_ENV: production
      DNSDOMAIN: ${DNSDOMAIN}
      CONSUL_ADDRESS: consul:8500
      TRACE_SERVICE_sNAME: transactionservice
      TRACE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NmY0ZDE1ZTg2OTYyMzg2NzA0NTEwOSIsImlhdCI6MTUwMDQ2NjQ1M30.r6BHvTt3RCkYsTe_U36lAED_t8xtJRKFFEgVAkN8jNE
    ports:
      - "8020:8020"
      - "9932:9932"
    restart: always
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  transactionmongo:
    image: ammar2017/mongo:latest
    deploy:
       mode: replicated
       replicas: 1
       placement:
           constraints: [node.role  ==  manager]
    ports:
      - "27013:27017"
    networks:
      - microservices
      - loadbalancer_default
    restart: always
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"

  transactionredis:
    image: redis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role  ==  manager]
    ports:
      - "6370:6379"
    networks:
      - microservices
      - loadbalancer_default
    restart: always
    extra_hosts:
      - "${DNSDOMAIN}:${DNSDOMAINIP}"
