version: '3'

networks:
  microservices:
    external: false
  loadbalancer:
    external: true

services:

  monitoring_default:
    image: monitoring_default/monitoring_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager]
    command: -H unix:///var/run/docker.sock
    networks:
      - loadbalancer_default
      - monitoring_default

  viz:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager]
    networks:
      - loadbalancer_default
      - monitoring_default
    ports:
      - 9090:8080
    restart: always
